const fs=require('fs'),path=require('path'),assert=require('assert');
const {chromium}=require(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES+'/playwright');
(async()=>{const root=path.resolve(__dirname,'..');const launch=()=>chromium.launch({executablePath:process.env.CHROMIUM_EXECUTABLE_PATH,args:JSON.parse(process.env.CHROMIUM_ARGS_JSON)});
for(const width of [320,390,768,1280]){const browser=await launch();const ctx=await browser.newContext({viewport:{width,height:844},reducedMotion:'reduce'});await ctx.route('**/*',r=>{let u=new URL(r.request().url());let f=root+u.pathname;return u.hostname==='127.0.0.1'&&fs.existsSync(f)?r.fulfill({body:fs.readFileSync(f),contentType:({html:'text/html',css:'text/css',js:'application/javascript',svg:'image/svg+xml',jpg:'image/jpeg',png:'image/png'})[f.split('.').pop()]||'application/octet-stream'}):r.abort()});const p=await ctx.newPage();
await p.goto('http://127.0.0.1/fit-protocol-vectors.html',{waitUntil:'networkidle'});assert.equal(await p.locator('h1').innerText(),'Liquid Intake');assert.equal(await p.locator('.liquid-cabinet>details').count(),7);
for(const key of ['v1','v6']){const file=p.locator('#vector-'+key);await file.locator('summary').first().click();assert(await file.evaluate(e=>e.open));assert(p.url().endsWith('fit-protocol-vectors.html'));assert.equal(await file.locator('.stack-source').getAttribute('href'),'fit-protocol-vector-'+key+'.html');await file.locator('summary').first().click();assert(!(await file.evaluate(e=>e.open)));}
await p.locator('.page-nav-arrow.next').click();assert(p.url().endsWith('fit-protocol-nutrition.html'));await p.goto('http://127.0.0.1/fit-meals.html',{waitUntil:'networkidle'});
const shape=await p.locator('.single-card .log-card').first().evaluate(e=>{let r=e.getBoundingClientRect();return {w:r.width,h:r.height,available:e.parentElement.clientWidth}});assert(shape.w>=shape.available-10,'Single card must fill the available content width');assert(shape.h<380,'Single item must be compact: '+JSON.stringify(shape));await p.screenshot({path:'/tmp/liquid-meals-'+width+'.png'});
await p.goto('http://127.0.0.1/fit-protocol-vector-v6.html',{waitUntil:'networkidle'});const tab=await p.locator('.focused-subtabs a.current').evaluate(e=>{let r=e.getBoundingClientRect(),p=e.parentElement.getBoundingClientRect();return {left:r.left,right:r.right,pl:p.left,pr:p.right}});assert(tab.left>=tab.pl-1&&tab.right<=tab.pr+1,'Active folder must be visible');await browser.close();}console.log('PASS: inline open/close, seven numbered folders, detail links, category page changes, active tab visibility and compact single cards at four widths.');})().catch(e=>{console.error(e);process.exit(1)});
