const fs=require('fs'),path=require('path'),assert=require('assert');const {chromium}=require(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES+'/playwright');
(async()=>{let checks=0;for(const width of [320,390,768,1280]){
const browser=await chromium.launch({executablePath:process.env.CHROMIUM_EXECUTABLE_PATH,args:JSON.parse(process.env.CHROMIUM_ARGS_JSON)});const context=await browser.newContext({viewport:{width,height:844},reducedMotion:'reduce'});
await context.route('**/*',async route=>{const u=new URL(route.request().url());if(u.hostname!=='127.0.0.1')return route.abort();const p=path.resolve(__dirname,'..')+u.pathname;const type={html:'text/html',css:'text/css',js:'application/javascript',jpg:'image/jpeg',png:'image/png',mp4:'video/mp4'}[p.split('.').pop()];await route.fulfill({status:fs.existsSync(p)?200:404,contentType:type,body:fs.existsSync(p)?fs.readFileSync(p):'Missing'})});
let shellWidth;for(const file of ['index.html','fit-protocol.html']){const page=await context.newPage();await page.goto('http://127.0.0.1/'+file,{waitUntil:'networkidle'});
const geometry=await page.evaluate(()=>{const box=s=>{const r=document.querySelector(s).getBoundingClientRect();return {x:r.x,y:r.y,width:r.width,height:r.height}};return {shell:box('.page-shell'),prev:box('.page-nav-arrow.prev'),next:box('.page-nav-arrow.next'),float:box('.encyclopedia-float'),headerLinks:document.querySelectorAll('.site-head .guidebook-access').length}});
assert.equal(geometry.headerLinks,0);assert(Math.abs(geometry.prev.y+geometry.prev.height/2-422)<1);assert(Math.abs(geometry.next.y+geometry.next.height/2-422)<1);assert(geometry.float.x>=0);assert(width-(geometry.float.x+geometry.float.width)<=16);assert(geometry.float.y+geometry.float.height<=844);assert(geometry.float.y>740);if(shellWidth)assert.equal(shellWidth,geometry.shell.width);shellWidth=geometry.shell.width;assert(await page.locator('.page-tabs').isVisible());
if(width===390||width===1280)await page.screenshot({path:'/tmp/project100-v2-qa/filing-'+file.replace('.html','')+'-'+width+'.png'});
checks++;await page.close();}await browser.close();}console.log('PASS:',checks,'shared shell, folder tabs, centered arrows and floating reference checks');})();
