const fs=require('fs'),path=require('path'),assert=require('assert');const {chromium}=require(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES+'/playwright');
(async()=>{const root=path.resolve(__dirname,'..'),browser=await chromium.launch({executablePath:process.env.CHROMIUM_EXECUTABLE_PATH,args:['--no-sandbox','--disable-dev-shm-usage']});
async function context(width,reduced='reduce'){const c=await browser.newContext({viewport:{width,height:844},reducedMotion:reduced});await c.route('**/*',r=>{const u=new URL(r.request().url()),f=root+decodeURIComponent(u.pathname);if(u.hostname!=='127.0.0.1'||!fs.existsSync(f))return r.abort();return r.fulfill({body:fs.readFileSync(f),contentType:({html:'text/html',css:'text/css',js:'application/javascript',json:'application/json',png:'image/png',jpg:'image/jpeg',svg:'image/svg+xml',woff2:'font/woff2'})[path.extname(f).slice(1)]||'application/octet-stream'})});return c}
const files=fs.readdirSync(root).filter(f=>f.endsWith('.html')&&fs.readFileSync(path.join(root,f),'utf8').includes('mobile-focus.css'));let checks=0;const errors=[];
for(const width of [320,390,768,1280]){const c=await context(width),p=await c.newPage();p.on('pageerror',e=>errors.push(e.message));for(const file of files){await p.goto('http://127.0.0.1/'+file,{waitUntil:'domcontentloaded'});await p.waitForTimeout(65);assert(!(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1)),width+' '+file+' page overflow');
for(const row of await p.locator('.carousel-row[data-motion]').all()){const info=await row.evaluate(r=>{const a=r.querySelector(':scope > :not([data-loop-copy])');return{w:r.clientWidth,card:a.getBoundingClientRect().width,gap:parseFloat(getComputedStyle(r).gap),single:r.parentElement.classList.contains('single-card')}});if(width<=900&&!info.single&&info.w)assert(info.card*2+info.gap<=info.w+2,width+' '+file+' needs two previews '+JSON.stringify(info));}checks++}
await c.close()}
const c=await context(390,'no-preference'),p=await c.newPage();p.on('pageerror',e=>errors.push(e.message));await p.goto('http://127.0.0.1/fit-workout.html',{waitUntil:'networkidle'});let row=p.locator('.carousel-row').first();await row.scrollIntoViewIfNeeded();await p.mouse.move(0,0);await p.waitForTimeout(250);const before=await row.evaluate(r=>r.scrollLeft);await p.waitForTimeout(1500);assert(await row.evaluate(r=>r.scrollLeft)>before+10,'Default continuous right-to-left motion');
await row.dispatchEvent('wheel',{deltaX:-80,deltaY:0});assert.equal(await row.getAttribute('data-motion-direction'),'-1');await p.waitForTimeout(2700);const reverse=await row.evaluate(r=>r.scrollLeft);await p.waitForTimeout(1200);assert(await row.evaluate(r=>r.scrollLeft)<reverse-8,'Reverse resumes after horizontal input');
await row.dispatchEvent('pointerdown',{clientX:180});await row.dispatchEvent('pointermove',{clientX:100});await p.dispatchEvent('body','pointerup',{clientX:100});assert.equal(await row.getAttribute('data-motion-direction'),'1');await p.waitForTimeout(2700);const swipe=await row.evaluate(r=>r.scrollLeft);await p.waitForTimeout(1000);assert(await row.evaluate(r=>r.scrollLeft)>swipe+7,'Swipe direction resumes');
await p.emulateMedia({reducedMotion:'reduce'});await p.waitForTimeout(200);const still=await row.evaluate(r=>r.scrollLeft);await p.waitForTimeout(1000);assert.equal(await row.evaluate(r=>r.scrollLeft),still,'Reduced motion stops');
await p.locator('[data-filter="arms"]').click();row=p.locator('.carousel-row').first();assert.equal(await row.getAttribute('data-motion'),'continuous','Filter lifecycle rebuilt');
await p.emulateMedia({reducedMotion:'no-preference'});await row.scrollIntoViewIfNeeded();await p.mouse.move(0,0);await p.waitForTimeout(200);const rebuilt=await row.evaluate(r=>r.scrollLeft);await p.waitForTimeout(1000);assert(await row.evaluate(r=>r.scrollLeft)>rebuilt+7,'Filtered rows resume automatically');
const qa=path.join(root,'..','mobile-focus-qa');fs.mkdirSync(qa,{recursive:true});for(const file of ['fit-workout.html','gear-gym.html','fit-meals.html','fit-protocol-vectors.html','index.html']){await p.goto('http://127.0.0.1/'+file,{waitUntil:'networkidle'});await p.emulateMedia({reducedMotion:'reduce'});const target=p.locator('.carousel-wrap').first();if(await target.count())await target.scrollIntoViewIfNeeded();await p.screenshot({path:path.join(qa,file.replace('.html','')+'-390.png')});}
assert.deepEqual(errors,[]);await browser.close();console.log('PASS:',checks,'page/viewport checks; two-preview widths; default motion; swipe/wheel direction; resumed motion; live reduced-motion toggle; filtered-row lifecycle.');})().catch(e=>{console.error(e);process.exit(1)});
