const fs=require('fs');const path=require('path');const repoRoot=path.resolve(__dirname,'..');const qaRoot=process.env.QA_OUTPUT_DIR||'/tmp/project100-v2-qa';fs.mkdirSync(qaRoot,{recursive:true});const assert=require('assert');const {chromium}=require(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES?process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES+'/playwright':'playwright');
(async()=>{const browserArgs=JSON.parse(process.env.CHROMIUM_ARGS_JSON||'["--no-sandbox"]');const b=await chromium.launch({executablePath:process.env.CHROMIUM_EXECUTABLE_PATH,args:browserArgs,headless:true});const ctx=await b.newContext({viewport:{width:390,height:844},reducedMotion:'reduce'});const root=repoRoot;const errors=[];
await ctx.route('**/*',async r=>{const u=new URL(r.request().url());if(u.hostname!=='127.0.0.1')return r.abort();const f=root+decodeURIComponent(u.pathname);const types={html:'text/html',css:'text/css',js:'application/javascript',png:'image/png',jpg:'image/jpeg',mp4:'video/mp4',pdf:'application/pdf'};return fs.existsSync(f)?r.fulfill({status:200,contentType:types[f.split('.').pop()]||'application/octet-stream',body:fs.readFileSync(f)}):r.fulfill({status:404,body:'missing'})});
const p=await ctx.newPage();p.on('pageerror',e=>errors.push(e.message));p.setDefaultTimeout(5000);const go=f=>p.goto('http://127.0.0.1:8765/'+f,{waitUntil:'networkidle'});let checks=0;
await go('fit-protocol.html');assert.equal(await p.locator('.protocol-file').count(),12);assert.equal(await p.locator('.deck-toolbar,.deck-bottom').count(),0);assert.equal(await p.locator('.site-head .guidebook-access').count(),0);assert.equal(await p.locator('.encyclopedia-float').getAttribute('href'),'fit-protocol-archive.html');assert.equal(await p.locator('.page-shell').count(),1);await go('fit-protocol.html#slide-fuel');assert(await p.locator('#slide-fuel details').evaluate(e=>e.open));await p.locator('.page-nav-arrow.next').click();assert(p.url().endsWith('fit-protocol-baseline.html'));await p.locator('.page-nav-arrow.prev').click();assert(p.url().endsWith('fit-protocol.html'));checks+=8;
await go('fit-protocol-archive.html');assert.equal(await p.locator('.site-destinations,.page-tabs,.encyclopedia-float').count(),0);assert.equal(await p.locator('.return-project').getAttribute('href'),'index.html');assert.equal(await p.locator('.book-navigation').count(),1);await p.locator('.book-navigation a[href="#book-index"]').click();assert(await p.locator('.reader-mobile-index').evaluate(e=>e.open));checks+=4;await p.locator('#readerSearch').fill('loose stools');await p.waitForTimeout(300);assert(await p.locator('#ch7').isVisible());assert(await p.locator('#ch7 mark').count()>0);await p.locator('#readerCategory').selectOption('Safety & Clinical');assert(await p.locator('#ch7').isVisible());assert.equal(await p.locator('#ch1:visible').count(),0);await p.locator('#readerSearch').fill('ZZZZ-NO-SOURCE-HIT');await p.waitForTimeout(300);assert((await p.locator('#readerResults').textContent()).includes('No matching'));await p.locator('#readerSearch').fill('');await p.locator('#readerCategory').selectOption('all');await p.waitForTimeout(300);assert.equal(await p.locator('.book-chapter[data-category]:visible').count(),21);checks+=4;
await go('fit-protocol-archive.html#ch4');await p.waitForTimeout(250);const rect=await p.locator('#ch4').boundingBox(),head=await p.locator('.site-head').boundingBox();assert(rect.y>=head.height-2 && rect.y<=head.height+35,JSON.stringify({rect,head}));await p.screenshot({path:qaRoot+'/reader-clock-mobile.png'});await p.reload({waitUntil:'networkidle'});assert(await p.locator('#resumeReading').isVisible());checks+=2;
await go('guidebook.html');await p.locator('[data-day=rest]').click();assert.equal(await p.locator('.clock-card[data-branch=training]:visible').count(),0);assert.equal(await p.locator('.clock-card[data-branch=rest]:visible').count(),10);await p.reload({waitUntil:'networkidle'});assert.equal(await p.locator('[data-day=rest]').getAttribute('aria-pressed'),'true');await p.screenshot({path:qaRoot+'/guidebook-rest-mobile.png'}); checks+=2;
await go('fit-workout.html?cat=arms');assert.equal(await p.locator('.filter[data-filter=arms]').getAttribute('aria-pressed'),'true');assert.equal(await p.locator('.log-card:not(.cat-arms)').count(),0);await p.locator('.filter[data-filter=resistance-bands]').click();assert(p.url().includes('cat=resistance-bands'));await p.goBack({waitUntil:'networkidle'});assert.equal(await p.locator('.filter[data-filter=arms]').getAttribute('aria-pressed'),'true');const media=p.locator('#logGrid .carousel-row > :not([data-loop-copy]) .log-media[data-yt]').first();await media.focus();await p.keyboard.press('Enter');assert(await media.locator('iframe').count()===1);checks+=3;
await go('encyclopedia-guidebook.html?utm_source=instagram#quickref');assert(p.url().endsWith('fit-protocol-archive.html?utm_source=instagram#annex1'),p.url());checks++;
await go('library.html');assert.equal(await p.locator('a[download]').count(),6);for(const a of await p.locator('a[download]').all()){const f=await a.getAttribute('href');assert(fs.existsSync(root+'/'+f))}checks++;
for(const width of [320,390,768,1280]){await p.setViewportSize({width,height:844});await go('fit-protocol-archive.html');assert(!(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1)),'reader overflow at '+width);await p.locator('#siteMenuTab').click();assert(await p.locator('#siteDrawer').evaluate(e=>!e.inert));await p.keyboard.press('Escape');assert(await p.locator('#siteDrawer').evaluate(e=>e.inert));await p.locator('#themeToggle').click();assert(!(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1)));checks+=2;}
assert.deepEqual(errors,[]);fs.writeFileSync(qaRoot+'/interaction-results.json',JSON.stringify({checks,errors},null,2));console.log('PASS:',checks,'V2.0 interaction checks; no runtime errors.');await b.close();})();
